image: WMF 5

version: 0.1.{build}

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /update(?:|d|s) readme\..*/

environment:
  PSGalleryApiKey:
    secure: Xpt1sogACnm41S2/1LmhjIl1zn/s1u1dcwNdhLcUh8RA8eOSGaMGB8Ce8B5svBzg
  CODECOV_TOKEN:
    secure: W18DapjYmwNINy8gyLl30FmNUIzLYE9K2hAMZhE3FJpa/ObmvB5t1d/xxgD0cn+R



install:
# Bootstrap PSDepend and Install Dependencies
- ps: |
    Install-PackageProvider -Name NuGet -MinimumVersion '2.8.5.201' -Force -Verbose
    Install-Module -Name PSDepend -Force -Verbose; Import-Module -Name PSDepend -Verbose
    Invoke-PSDepend '.\REQUIREMENTS.psd1' -Force -Verbose



build_script:
- ps: Invoke-psake '.\.scripts\build.ps1' -Properties @{'SkipBootStrap' = $true}



after_test:
# Upload coverage report to Codecov.io
- ps: |
    & "${env:Temp}\Codecov\codecov.exe" -f .\dev\CodeCoverage.xml



deploy_script:
# If build was started by pushed tag; deploy it.
- ps: |
    Write-Host "[AppVeyor] APPVEYOR_REPO_TAG: ${env:APPVEYOR_REPO_TAG}" -Foregroundcolor 'Blue' -BackgroundColor 'Magenta'
    if ($env:APPVEYOR_REPO_TAG -eq 'true') { Invoke-PSDeploy -Path '.\.scripts\deploy.ps1' -Force }